name: run ws_pda.py
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run_schedule:
    runs_on: ubuntu-latest
    steps:
      - name: check conteudo repositorio
        uses: actions/checkout@v3
      - name: instalar python
        uses: actions/setup-python@v4
      - name: instalar os pacotes do requirements.txt
        uses: python -m pip install pip install -r requirements.txt
      - name: executar arquivo de scrapping
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python ws_pda.py