name: run ws_pda.py
on:
  workflow_dispatch:
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '0 */4 * * *'
env:
    LANG: "pt_BR.UTF-8"
jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: pt_BR.UTF-8
        run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
      - name: date
        run: |
          date
      - name: check conteudo repositorio
        uses: actions/checkout@v3
      - name: instalar python
        uses: actions/setup-python@v4
      - name: instalar os pacotes do requirements.txt
        run: python -m pip install pip install -r requirements.txt
      - name: executar arquivo de scrapping
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          API_TELEGRAM: ${{ secrets.API_TELEGRAM }}
          CHAT_ID_TELEGRAM: ${{ secrets.CHAT_ID_TELEGRAM }}
        run: python ws_pda.py